### ISSUE TITLE
64位win7、32位python3.X能运行成功吗？

### ISSUE THREAD

**Issue by quzhe** [lovelylain/pyctp#53]
你好，我的环境里会报这个错：
Traceback (most recent call last):
  File "D:/workspace/python/mytrade/demo.py", line 77, in <module>
    if __name__=="__main__": main()
  File "D:/workspace/python/mytrade/demo.py", line 67, in main
    user.Create("data")
  File "MdApi.pyx", line 36, in ctp._MdApi.MdApi.Create (ctp/MdApi.cpp:987)
TypeError: expected bytes, str found

64位win7、32位python2.7没有问题。

**Comment by quzhe** [comment]
直接用的例子demp.py，将print改成了函数，其它没变
